version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Виправлена орфографічна помилка
  adminer:
    container_name: db_adminer
    image: adminer
    restart: always
    depends_on:
      - postgres  # Виправлено назву залежного сервісу
    ports:
      - "8080:8080"
volumes:
  postgres_data:  # Виправлена орфографічна помилка
